services:
  recycling-robot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    devices:
      - /dev/video10:/dev/video10
    group_add:
      - "video"
    environment:
      - PYTHONUNBUFFERED=1
      - CAMERA_DEVICE=/dev/video10
    privileged: true
    volumes:
      - ./src:/workspace/src
      - ./launch:/workspace/launch
      - ./models:/workspace/models
    working_dir: /workspace
    tty: true
    stdin_open: true
