services:
  recycling-robot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
    group_add:
      - "video"
    environment:
      - PYTHONUNBUFFERED=1
    # For live-edit instead of COPY at build, uncomment:
    # volumes:
    #   - ./src:/workspace/src
