services:
  backend:
    build: ./backend
    command: ["python", "app.py"]
    volumes:
      - ./backend:/app
      - shared_data:/data  # Shared volume for database
      - shared_frames:/shared  # Shared volume for camera frames
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - API_BASE_URL=${API_BASE_URL}
    networks:
      - robot_network

  ros2:
    build: ./ros2
    volumes:
      - ./ros2/src:/workspace/ros2_ws/src
      - shared_data:/data
      - shared_frames:/shared  # Shared volume for camera frames
      - /dev:/dev                       # Full device access for GPIO
      - /sys/class/gpio:/sys/class/gpio # GPIO sysfs interface
      - /sys/devices:/sys/devices       # Device tree access
    privileged: true
    network_mode: host  # Use host network for direct hardware access
    group_add:
      - video
      - gpio
      - dialout
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip4:/dev/gpiochip4"  # Pi 5 compatibility
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - API_BASE_URL=http://localhost:8000
      - GPIOMEM=1                       # Enable gpiomem for RPi.GPIO
    depends_on:
      - backend
    command: ["tail", "-f", "/dev/null"]

  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8000}
      - VITE_VIDEO_URL=${VITE_VIDEO_URL:-http://localhost:8080/video_feed}
    networks:
      - robot_network
    depends_on:
      - backend

# Define custom network and shared volumes
networks:
  robot_network:
    driver: bridge

volumes:
  shared_data:
  shared_frames: