services:
  recycling-robot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_DOMAIN_ID=0
      # Configure camera to use host stream
      - CAMERA_STREAM_URL=http://host.docker.internal:8554/stream.mjpg
    # Remove device mappings - camera runs on host now
    # devices:
    #   - /dev/video3:/dev/video3
    extra_hosts:
      # Allow container to reach Pi host
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/workspace/src
      - ./launch:/workspace/launch
      - ./models:/workspace/models
    working_dir: /workspace
    # Remove privileged mode - not needed for host streams
    # privileged: true
    networks:
      - robot-net

  # Optional: Add Pi-hole or other host services here
  # that might be running alongside the camera

networks:
  robot-net:
    driver: bridge

# Optional: Health check service to monitor camera stream
  camera-monitor:
    image: curlimages/curl:latest
    depends_on:
      - recycling-robot
    command: >
      sh -c "
        while true; do
          echo 'Checking camera stream...'
          curl -f http://host.docker.internal:8554/stream.mjpg --max-time 5 || echo 'Stream check failed'
          sleep 30
        done
      "
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - robot-net