services:
  backend:
    build: ./backend
    command: ["python", "app.py"]
    volumes:
      - ./backend:/app
      - shared_data:/data  # Shared volume for database
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - API_BASE_URL=${API_BASE_URL}
    networks:
      - robot_network

  ros2:
    build: ./ros2
    volumes:
      - ./ros2/src:/workspace/ros2_ws/src
      - shared_data:/data
    privileged: true
    group_add:
      - video
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    environment:
      - API_BASE_URL=${API_BASE_URL}
    networks:
      - robot_network
    depends_on:
      - backend
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8080:8080"

  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8000}
      - VITE_VIDEO_URL=${VITE_VIDEO_URL:-http://localhost:8080/video_feed}
    networks:
      - robot_network
    depends_on:
      - backend

# Define custom network and shared volume
networks:
  robot_network:
    driver: bridge

volumes:
  shared_data:
