services:
  ros2:
    build: ./ros2
    volumes:
      - ./ros2/src:/workspace/ros2_ws/src
    network_mode: host
    privileged: true   # Needed for camera access
    devices:
      - "/dev/video0:/dev/video0"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
