services:
  backend:
    build: ./backend
    command: ["python", "app.py"]
    volumes:
      - ./backend:/app
      - shared_data:/data  # Shared volume for database
      - shared_frames:/shared  # Shared volume for camera frames
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - API_BASE_URL=${API_BASE_URL}
    networks:
      - robot_network

  ros2:
    build: ./ros2
    volumes:
      - ./ros2/src:/workspace/ros2_ws/src
      - shared_data:/data
      - shared_frames:/shared  # Shared volume for camera frames
      - /var/run/pigpiod.if:/var/run/pigpiod.if
    privileged: true
    user: robot
    network_mode: host
    group_add:
      - video
      - gpio
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiomem0:/dev/gpiomem0"
      - "/dev/gpiomem1:/dev/gpiomem1"
      - "/dev/gpiomem2:/dev/gpiomem2"
      - "/dev/gpiomem3:/dev/gpiomem3"
      - "/dev/gpiomem4:/dev/gpiomem4"
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip10:/dev/gpiochip10"
      - "/dev/gpiochip11:/dev/gpiochip11"
      - "/dev/gpiochip12:/dev/gpiochip12"
      - "/dev/gpiochip13:/dev/gpiochip13"
    environment:
      - API_BASE_URL=http://localhost:8000
      - GPIOZERO_PIN_FACTORY=rpigpio
      - RPI_GPIO_PWM_FREQ=1000
      - HOST_GPIO_URL=http://localhost:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8080:8080"

  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8000}
      - VITE_VIDEO_URL=${VITE_VIDEO_URL:-http://localhost:8080/video_feed}
    networks:
      - robot_network
    depends_on:
      - backend

# Define custom network and shared volumes
networks:
  robot_network:
    driver: bridge

volumes:
  shared_data:
  shared_frames:
