services:
  ros2:
    build:
      context: ..
      dockerfile: backend/ros2.Dockerfile
    working_dir: /workspace/ros2_ws
    devices:
      - /dev/video0:/dev/video0
    command: tail -f /dev/null

  api:
    build:
      context: ..
      dockerfile: backend/api.Dockerfile
    ports:
      - "8000:8000"
