# Camera configuration for Recycling Robot

# Camera node parameters
camera_node:
  ros__parameters:
    device_id: 0
    width: 640
    height: 480
    fps: 10.0
    publish_rate: 0.1  # 10 FPS = 0.1s interval
    image_quality: 85
    snapshot_enabled: true
    snapshot_path: '/shared/current_frame.jpg'
    retry_attempts: 3
    retry_delay: 1.0

# Classifier node parameters
classifier_node:
  ros__parameters:
    model_path: 'src/recycling_robot/recycling_robot/models/recycler.pt'
    confidence_threshold: 0.7
    inference_interval: 3.0

# Mock camera node parameters
mock_camera_node:
  ros__parameters:
    publish_rate: 3.0
    image_quality: 85
    auto_fallback: true
